# Generated by Django 4.2.9 on 2024-10-08 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Aceptada'), (3, 'Rechazada')], default=1),
        ),
        migrations.AddField(
            model_name='devoluciones',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('contacto', models.IntegerField()),
                ('tipo_pago', models.IntegerField(choices=[(1, 'Tarjeta de crédito'), (2, 'Tarjeta de débito'), (3, 'Efectivo')])),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
