# Generated by Django 4.2.9 on 2024-10-08 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_carouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagada'), (3, 'Rechazada')], default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
