# Generated by Django 4.2.9 on 2024-10-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_detalleventa_subtotal_detalleventa_id_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='etiqueta',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='productosubcategoria',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='productosubcategoria',
            name='id_sub_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.subcategoriaetiqueta'),
        ),
        migrations.AlterField(
            model_name='subcategoriaetiqueta',
            name='id_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoriaetiqueta'),
        ),
        migrations.CreateModel(
            name='ProductoTallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('id_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tallas')),
            ],
        ),
    ]
