# Generated by Django 4.2.7 on 2024-10-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_tallas_remove_producto_etiqueta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
    ]
