# Generated by Django 4.2.9 on 2024-10-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_alter_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoriaetiqueta',
            name='id_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria'),
        ),
    ]
