# Generated by Django 4.2.9 on 2024-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_alter_subcategoriaetiqueta_id_categoria_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Pagada'), (3, 'Rechazada'), (4, 'Enviado')], default=1),
        ),
    ]
