# Generated by Django 4.2.7 on 2024-10-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_alter_venta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
