# Generated by Django 4.2.9 on 2024-10-15 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_venta_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.categoriaetiqueta'),
        ),
        migrations.AlterField(
            model_name='productosubcategoria',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='productosubcategoria',
            name='id_sub_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.subcategoriaetiqueta'),
        ),
        migrations.AlterField(
            model_name='productotallas',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.producto'),
        ),
        migrations.AlterField(
            model_name='productotallas',
            name='id_talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.tallas'),
        ),
        migrations.AlterField(
            model_name='subcategoriaetiqueta',
            name='id_categoria_etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.categoriaetiqueta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
