# Generated by Django 4.2.7 on 2024-10-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0027_devolucion_delete_devoluciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones_fotos/'),
        ),
    ]
